{
  "swagger": "2.0",
  "info": {
    "description": "Afiliados CRUD API",
    "version": "1.0",
    "title": "Afiliados API",
    "termsOfService": "https://www.nttdata.com/global/en/",
    "contact": {
      "name": "Miguel",
      "url": "https://github.com/Elmigue10",
      "email": "miguelvalbuena1026@gmail.com"
    },
    "license": {
      "name": "LICENSE",
      "url": "http://license.com"
    }
  },
  "host": "localhost:8080",
  "basePath": "/",
  "tags": [
    {
      "name": "afiliado-controller",
      "description": "Afiliado Controller"
    }
  ],
  "paths": {
    "/api/v1/afiliado": {
      "get": {
        "tags": [
          "afiliado-controller"
        ],
        "summary": "Listar todos los afiliados",
        "operationId": "getAllUsingGET",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/AfiliadoDto"
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        }
      },
      "post": {
        "tags": [
          "afiliado-controller"
        ],
        "summary": "Guardar un nuevo afiliado",
        "operationId": "saveAfiliadoUsingPOST",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "afiliadoDto",
            "description": "afiliadoDto",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AfiliadoDto"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          },
          "201": {
            "description": "Created"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        }
      },
      "put": {
        "tags": [
          "afiliado-controller"
        ],
        "summary": "Actualizar un afiliado",
        "operationId": "updatedAfiliadoUsingPUT",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "afiliadoDto",
            "description": "afiliadoDto",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AfiliadoDto"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          },
          "201": {
            "description": "Created"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/api/v1/afiliado/filtrarFechaCreacion": {
      "get": {
        "tags": [
          "afiliado-controller"
        ],
        "summary": "Filtrar busqueda por intervalo de fecha de creacion",
        "operationId": "filtrarFechaCreacionUsingGET",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "fromDate",
            "in": "query",
            "description": "fromDate",
            "required": true,
            "type": "string"
          },
          {
            "name": "toDate",
            "in": "query",
            "description": "toDate",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/AfiliadoDto"
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/api/v1/afiliado/filtrarIdentificacion": {
      "get": {
        "tags": [
          "afiliado-controller"
        ],
        "summary": "Filtrar busqueda por numero de identificacion",
        "operationId": "findByNumeroIdentificacionUsingGET",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "numeroIdentificacion",
            "in": "query",
            "description": "numeroIdentificacion",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/AfiliadoDto"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/api/v1/afiliado/filtrarUsuarioCreacion": {
      "get": {
        "tags": [
          "afiliado-controller"
        ],
        "summary": "Filtrar busqueda por usuario de creacion",
        "operationId": "filtrarByUsuarioCreacionUsingGET",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "usuarioCreacion",
            "in": "query",
            "description": "usuarioCreacion",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/AfiliadoDto"
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/api/v1/afiliado/{id}": {
      "get": {
        "tags": [
          "afiliado-controller"
        ],
        "summary": "Buscar afiliado por id",
        "operationId": "findByIdUsingGET",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "id",
            "required": true,
            "type": "integer",
            "format": "int32"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/AfiliadoDto"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        }
      },
      "delete": {
        "tags": [
          "afiliado-controller"
        ],
        "summary": "Eliminar un afiliado",
        "operationId": "deleteAfiliadoByIdUsingDELETE",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "id",
            "required": true,
            "type": "integer",
            "format": "int32"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          },
          "204": {
            "description": "No Content"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    }
  },
  "definitions": {
    "AfiliadoDto": {
      "type": "object",
      "properties": {
        "activo": {
          "type": "string"
        },
        "afiliadoId": {
          "type": "integer",
          "format": "int32"
        },
        "estadoCuenta": {
          "type": "string"
        },
        "fechaCreacion": {
          "type": "string"
        },
        "fechaUltimaModificacion": {
          "type": "string"
        },
        "numeroCuenta": {
          "type": "string"
        },
        "numeroIdentificacion": {
          "type": "string"
        },
        "primerApellido": {
          "type": "string"
        },
        "primerNombre": {
          "type": "string"
        },
        "riesgoCat": {
          "type": "string"
        },
        "segundoApellido": {
          "type": "string"
        },
        "segundoNombre": {
          "type": "string"
        },
        "tipoIdentificacion": {
          "type": "string"
        },
        "usuarioCreacion": {
          "type": "string"
        },
        "usuarioUltimaModificacion": {
          "type": "string"
        }
      },
      "title": "AfiliadoDto"
    }
  }
}